// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(kovanicaFFI)
import kovanicaFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_kovanica_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_kovanica_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }

    init(rawBufferPointer: UnsafeRawBufferPointer) {
        self.init(
            len: Int32(rawBufferPointer.count),
            data: rawBufferPointer.baseAddress?.assumingMemoryBound(to: UInt8.self)
        )
    }
}

// Converter for `&[u8]` / `[ByRef] bytes` arguments.
//
// Conforms to `FfiConverter` so the compiler enforces the full converter
// method set. Only the scope-bound `lower(_:_body:)` overload is sound —
// zero-copy byte buffers only flow foreign -> Rust, and only in argument
// position. The four protocol-witness methods (`lift`, `lower`, `read`,
// `write`) `fatalError` at runtime if anyone reaches them.
//
// The scope-bound `lower` takes a closure because the `ForeignBytes`
// pointer is only guaranteed valid for the duration of
// `Data.withUnsafeBytes`. Callers must run the full FFI call inside
// the closure body.
fileprivate enum FfiConverterByRefBytes: FfiConverter {
    typealias SwiftType = Data
    typealias FfiType = ForeignBytes

    static func lower<R>(_ value: Data, _ body: (ForeignBytes) throws -> R) rethrows -> R {
        return try value.withUnsafeBytes { rawBuf in
            try body(ForeignBytes(rawBufferPointer: rawBuf))
        }
    }

    static func lower(_ value: Data) -> ForeignBytes {
        fatalError("ByRef bytes cannot use the plain lower: returning ForeignBytes escapes the Data.withUnsafeBytes scope. Use the scope-bound lower(_:_body:) overload instead.")
    }

    static func lift(_ value: ForeignBytes) throws -> Data {
        fatalError("ByRef bytes cannot be lifted: zero-copy &[u8] only flows foreign->Rust")
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        fatalError("ByRef bytes cannot be read from a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }

    static func write(_ value: Data, into buf: inout [UInt8]) {
        fatalError("ByRef bytes cannot be written to a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureKovanicaFfiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt16: FfiConverterPrimitive {
    typealias FfiType = UInt16
    typealias SwiftType = UInt16

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt16 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        // Use Swift's native UTF-8 decoder; `String(bytes:encoding:.utf8)` goes
        // through Foundation's NSString and silently strips a leading U+FEFF BOM.
        // Invalid UTF-8 substitutes U+FFFD instead of trapping (unreachable
        // given Rust's `String` invariant).
        return String(decoding: bytes, as: UTF8.self)
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        // See `lift` above for why we avoid Foundation's NSString-backed decoder here.
        return String(decoding: try readBytes(&buf, count: Int(len)), as: UTF8.self)
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




/**
 * A Kovanica light node: ledger + mempool + hybrid validator identity.
 *
 * Sync model for mobile: call [`Self::export_blocks`] to hand peers your
 * blocks, feed peer bytes into [`Self::receive_blocks`]. Everything else —
 * balances, bonding, staked production — is local computation over verified
 * history only.
 *
 * SPV model: [`Self::export_light_sync`] carries the selected chain as
 * verified headers plus one compact block filter per block; a phone can
 * accept that blob ([`Self::receive_light_sync`]) without any full payload,
 * then watch addresses via [`Self::filter_matches`] and pull only matching
 * full blocks through the regular block channel. Transaction inclusion is
 * proved with [`Self::prove_tx`] / [`Self::verify_tx_proof`].
 */
public protocol LightNodeProtocol: AnyObject, Sendable {
    
    /**
     * Spendable balance of an address: 64-hex or `kvnc…dag` form.
     */
    func balanceOfAddress(address: String) throws  -> String
    
    /**
     * Spendable balance of actor `seed` in atoms, as a decimal string
     * (balances are u128; strings avoid FFI integer truncation).
     */
    func balanceOfSeed(seed: UInt64) throws  -> String
    
    /**
     * Summary of one block by lowercase-hex id.
     */
    func blockById(idHex: String) throws  -> BlockInfo?
    
    /**
     * Number of blocks in the DAG, including genesis.
     */
    func blockCount() throws  -> UInt32
    
    /**
     * The compact filter of a known block as a blob
     * (`k || n || len || data`). Match addresses with
     * [`Self::filter_matches`].
     */
    func blockFilter(blockIdHex: String) throws  -> Data
    
    /**
     * Bond `amount` atoms of actor `seed`'s spendable coins to THIS node's
     * validator key, sealing both the sizing split (if needed) and the bond
     * transaction in mined PoW blocks. Returns the bond tx id, lowercase hex.
     *
     * A bond freezes whole coin(s): the flow splits a larger coin first so
     * exactly `amount` is frozen and the remainder stays spendable.
     */
    func bondStake(seed: UInt64, amount: UInt64) throws  -> String
    
    /**
     * The current chain height (selected tip's blue score).
     */
    func chainHeight() throws  -> UInt64
    
    /**
     * Enable hybrid admission: blocks enter by PoW or by eligible VRF draw.
     *
     * `rate_num/rate_den` scales slot frequency relative to bonded share
     * (`1/1` = one expected win per block at full supply); `nominal_work`
     * pins staked-block weight (keep tiny so mining stays king of chain
     * selection); `retarget` adopts the default difficulty-retargeting pin
     * for PoW-path work claims.
     */
    func enableHybrid(rateNum: UInt64, rateDen: UInt64, nominalWork: U128Parts, retarget: Bool) throws 
    
    /**
     * Every known block as a wire-format blob (framed count + records, VRF
     * bundles included). Hand this to a peer; idempotent on their side.
     */
    func exportBlocks()  -> Data
    
    /**
     * The selected chain as verified headers + per-block filters: everything
     * a phone needs to track payments without full payloads.
     */
    func exportLightSync()  -> Data
    
    /**
     * Whether `address` MIGHT appear in the filtered block (Golomb-Rice
     * false positives are possible; a miss is definitive).
     */
    func filterMatches(filterBlob: Data, address: String) throws  -> Bool
    
    /**
     * Whether hybrid admission is active.
     */
    func hybridEnabled()  -> Bool
    
    /**
     * Replace state with a snapshot from `path`. If this node has a hybrid
     * policy active, replay runs under it so staked-VRF blocks keep their
     * original ids; plain (pre-hybrid) snapshots load normally either way.
     */
    func loadSnapshot(path: String) throws 
    
    /**
     * This validator's bonded stake (tip view), in atoms.
     */
    func myStake() throws  -> UInt64
    
    /**
     * Earliest height at which bonded stake unlocks next (`None` when
     * everything already has). Compare against [`Self::chain_height`].
     */
    func pendingUnbondHeight() throws  -> UInt64?
    
    /**
     * Pack pending mempool transactions into the next block: tries the
     * staked-VRF draw first, falls back to PoW. `None` when nothing is pending.
     */
    func produceBlock() throws  -> BlockInfo?
    
    /**
     * Produce a block even with an empty mempool (coinbase-only when a miner
     * seed is set). Staked draw first, PoW fallback — this is the phone's
     * steady-state heartbeat.
     */
    func produceEmptyBlock() throws  -> BlockInfo
    
    /**
     * A Merkle-inclusion proof for `tx_id` inside block `block_id_hex`,
     * encoded as a blob. `None` when either is unknown or the tx is absent.
     */
    func proveTx(blockIdHex: String, txIdHex: String) throws  -> Data?
    
    /**
     * Apply a blob produced by [`Self::export_blocks`] (or any full node
     * speaking the same format). Records apply topologically; already-known
     * blocks are skipped. Returns how many were newly applied.
     */
    func receiveBlocks(blob: Data) throws  -> UInt32
    
    /**
     * Accept a light-sync blob: header chain is verified for linkage,
     * monotonic timestamps and rising blue work (`require_pow` off — hybrid
     * staked blocks carry nominal work). Returns accepted header count.
     */
    func receiveLightSync(blob: Data) throws  -> UInt32
    
    /**
     * Write a full snapshot (UTXO + stake registry + blocks) to `path`.
     */
    func saveSnapshot(path: String) throws 
    
    /**
     * The selected (heaviest) tip, lowercase hex.
     */
    func selectedTip() throws  -> String
    
    /**
     * Transfer `amount` from actor `from_seed` to `to_seed`, sealed
     * immediately in a mined block.
     */
    func send(fromSeed: UInt64, amount: UInt64, toSeed: UInt64) throws  -> SendReceipt
    
    /**
     * Transfer using an imported secret: the wallet passes its 32-byte
     * ed25519 seed as hex; the secret is used for this call only and never
     * stored. `to_address` accepts 64-hex or `kvnc…dag` form.
     */
    func sendFrom(signingSecretHex: String, amount: UInt64, toAddress: String) throws  -> SendReceipt
    
    /**
     * Receive the per-block subsidy coinbase on produced blocks under this
     * actor seed.
     */
    func setMinerSeed(seed: UInt64) throws 
    
    /**
     * Adopt a validator identity from a 32-byte VRF seed. Bond stake via
     * [`Self::bond_stake`] before production draws can win.
     */
    func setValidatorSeed(seed: Data) throws 
    
    /**
     * Whether `address` MIGHT appear in the given light-synced block,
     * answered from locally stored filters (`None` = block not synced).
     * A `true` is a probabilistic hit worth fetching full blocks for.
     */
    func syncedFilterMatches(blockIdHex: String, address: String) throws  -> Bool?
    
    /**
     * Highest height among light-synced headers (`None` before any sync).
     */
    func syncedHeight()  -> UInt64?
    
    /**
     * Current tip set, lowercase hex.
     */
    func tips() throws  -> [String]
    
    /**
     * Total bonded stake across all validators (tip view), in atoms.
     */
    func totalStake() throws  -> UInt64
    
    /**
     * Unbond `amount` of this validator's stake back to the seed actor's own
     * address. Only matured bonds count (`UNBOND_MATURITY` blue heights after
     * bonding); oldest bonds are released first, change stays unfrozen.
     * Sealed immediately in a mined block.
     */
    func unbond(fromSeed: UInt64, amount: UInt64) throws  -> SendReceipt
    
    /**
     * This validator's VRF public key, lowercase hex, if a seed was set.
     */
    func validatorPublicKeyHex()  -> String?
    
    /**
     * Verify an inclusion-proof blob against the light-synced header of
     * `block_id_hex`: the proof must verify internally AND its merkle root
     * must equal the header's root. Unknown block → error.
     */
    func verifyTxProof(proofBlob: Data, blockIdHex: String) throws  -> Bool
    
}
/**
 * A Kovanica light node: ledger + mempool + hybrid validator identity.
 *
 * Sync model for mobile: call [`Self::export_blocks`] to hand peers your
 * blocks, feed peer bytes into [`Self::receive_blocks`]. Everything else —
 * balances, bonding, staked production — is local computation over verified
 * history only.
 *
 * SPV model: [`Self::export_light_sync`] carries the selected chain as
 * verified headers plus one compact block filter per block; a phone can
 * accept that blob ([`Self::receive_light_sync`]) without any full payload,
 * then watch addresses via [`Self::filter_matches`] and pull only matching
 * full blocks through the regular block channel. Transaction inclusion is
 * proved with [`Self::prove_tx`] / [`Self::verify_tx_proof`].
 */
open class LightNode: LightNodeProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_kovanica_ffi_fn_clone_lightnode(self.handle, $0) }
    }
    /**
     * Bring up a fresh node at genesis with `config`.
     */
public convenience init(config: LightConfig)throws  {
    let handle =
        try rustCallWithError(FfiConverterTypeLightNodeError_lift) {
        uniffiCallStatus in
    uniffi_kovanica_ffi_fn_constructor_lightnode_new(
        FfiConverterTypeLightConfig_lower(config),uniffiCallStatus
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_kovanica_ffi_fn_free_lightnode(handle, $0) }
    }

    

    
    /**
     * Spendable balance of an address: 64-hex or `kvnc…dag` form.
     */
open func balanceOfAddress(address: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeLightNodeError_lift) {
        uniffiCallStatus in
    uniffi_kovanica_ffi_fn_method_lightnode_balance_of_address(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(address),uniffiCallStatus
    )
})
}
    
    /**
     * Spendable balance of actor `seed` in atoms, as a decimal string
     * (balances are u128; strings avoid FFI integer truncation).
     */
open func balanceOfSeed(seed: UInt64)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeLightNodeError_lift) {
        uniffiCallStatus in
    uniffi_kovanica_ffi_fn_method_lightnode_balance_of_seed(
            self.uniffiCloneHandle(),
        FfiConverterUInt64.lower(seed),uniffiCallStatus
    )
})
}
    
    /**
     * Summary of one block by lowercase-hex id.
     */
open func blockById(idHex: String)throws  -> BlockInfo?  {
    return try  FfiConverterOptionTypeBlockInfo.lift(try rustCallWithError(FfiConverterTypeLightNodeError_lift) {
        uniffiCallStatus in
    uniffi_kovanica_ffi_fn_method_lightnode_block_by_id(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(idHex),uniffiCallStatus
    )
})
}
    
    /**
     * Number of blocks in the DAG, including genesis.
     */
open func blockCount()throws  -> UInt32  {
    return try  FfiConverterUInt32.lift(try rustCallWithError(FfiConverterTypeLightNodeError_lift) {
        uniffiCallStatus in
    uniffi_kovanica_ffi_fn_method_lightnode_block_count(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
    /**
     * The compact filter of a known block as a blob
     * (`k || n || len || data`). Match addresses with
     * [`Self::filter_matches`].
     */
open func blockFilter(blockIdHex: String)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeLightNodeError_lift) {
        uniffiCallStatus in
    uniffi_kovanica_ffi_fn_method_lightnode_block_filter(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(blockIdHex),uniffiCallStatus
    )
})
}
    
    /**
     * Bond `amount` atoms of actor `seed`'s spendable coins to THIS node's
     * validator key, sealing both the sizing split (if needed) and the bond
     * transaction in mined PoW blocks. Returns the bond tx id, lowercase hex.
     *
     * A bond freezes whole coin(s): the flow splits a larger coin first so
     * exactly `amount` is frozen and the remainder stays spendable.
     */
open func bondStake(seed: UInt64, amount: UInt64)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeLightNodeError_lift) {
        uniffiCallStatus in
    uniffi_kovanica_ffi_fn_method_lightnode_bond_stake(
            self.uniffiCloneHandle(),
        FfiConverterUInt64.lower(seed),
        FfiConverterUInt64.lower(amount),uniffiCallStatus
    )
})
}
    
    /**
     * The current chain height (selected tip's blue score).
     */
open func chainHeight()throws  -> UInt64  {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeLightNodeError_lift) {
        uniffiCallStatus in
    uniffi_kovanica_ffi_fn_method_lightnode_chain_height(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
    /**
     * Enable hybrid admission: blocks enter by PoW or by eligible VRF draw.
     *
     * `rate_num/rate_den` scales slot frequency relative to bonded share
     * (`1/1` = one expected win per block at full supply); `nominal_work`
     * pins staked-block weight (keep tiny so mining stays king of chain
     * selection); `retarget` adopts the default difficulty-retargeting pin
     * for PoW-path work claims.
     */
open func enableHybrid(rateNum: UInt64, rateDen: UInt64, nominalWork: U128Parts, retarget: Bool)throws   {try rustCallWithError(FfiConverterTypeLightNodeError_lift) {
        uniffiCallStatus in
    uniffi_kovanica_ffi_fn_method_lightnode_enable_hybrid(
            self.uniffiCloneHandle(),
        FfiConverterUInt64.lower(rateNum),
        FfiConverterUInt64.lower(rateDen),
        FfiConverterTypeU128Parts_lower(nominalWork),
        FfiConverterBool.lower(retarget),uniffiCallStatus
    )
}
}
    
    /**
     * Every known block as a wire-format blob (framed count + records, VRF
     * bundles included). Hand this to a peer; idempotent on their side.
     */
open func exportBlocks() -> Data  {
    return try!  FfiConverterData.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_kovanica_ffi_fn_method_lightnode_export_blocks(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
    /**
     * The selected chain as verified headers + per-block filters: everything
     * a phone needs to track payments without full payloads.
     */
open func exportLightSync() -> Data  {
    return try!  FfiConverterData.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_kovanica_ffi_fn_method_lightnode_export_light_sync(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
    /**
     * Whether `address` MIGHT appear in the filtered block (Golomb-Rice
     * false positives are possible; a miss is definitive).
     */
open func filterMatches(filterBlob: Data, address: String)throws  -> Bool  {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeLightNodeError_lift) {
        uniffiCallStatus in
    uniffi_kovanica_ffi_fn_method_lightnode_filter_matches(
            self.uniffiCloneHandle(),
        FfiConverterData.lower(filterBlob),
        FfiConverterString.lower(address),uniffiCallStatus
    )
})
}
    
    /**
     * Whether hybrid admission is active.
     */
open func hybridEnabled() -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_kovanica_ffi_fn_method_lightnode_hybrid_enabled(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
    /**
     * Replace state with a snapshot from `path`. If this node has a hybrid
     * policy active, replay runs under it so staked-VRF blocks keep their
     * original ids; plain (pre-hybrid) snapshots load normally either way.
     */
open func loadSnapshot(path: String)throws   {try rustCallWithError(FfiConverterTypeLightNodeError_lift) {
        uniffiCallStatus in
    uniffi_kovanica_ffi_fn_method_lightnode_load_snapshot(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(path),uniffiCallStatus
    )
}
}
    
    /**
     * This validator's bonded stake (tip view), in atoms.
     */
open func myStake()throws  -> UInt64  {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeLightNodeError_lift) {
        uniffiCallStatus in
    uniffi_kovanica_ffi_fn_method_lightnode_my_stake(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
    /**
     * Earliest height at which bonded stake unlocks next (`None` when
     * everything already has). Compare against [`Self::chain_height`].
     */
open func pendingUnbondHeight()throws  -> UInt64?  {
    return try  FfiConverterOptionUInt64.lift(try rustCallWithError(FfiConverterTypeLightNodeError_lift) {
        uniffiCallStatus in
    uniffi_kovanica_ffi_fn_method_lightnode_pending_unbond_height(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
    /**
     * Pack pending mempool transactions into the next block: tries the
     * staked-VRF draw first, falls back to PoW. `None` when nothing is pending.
     */
open func produceBlock()throws  -> BlockInfo?  {
    return try  FfiConverterOptionTypeBlockInfo.lift(try rustCallWithError(FfiConverterTypeLightNodeError_lift) {
        uniffiCallStatus in
    uniffi_kovanica_ffi_fn_method_lightnode_produce_block(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
    /**
     * Produce a block even with an empty mempool (coinbase-only when a miner
     * seed is set). Staked draw first, PoW fallback — this is the phone's
     * steady-state heartbeat.
     */
open func produceEmptyBlock()throws  -> BlockInfo  {
    return try  FfiConverterTypeBlockInfo_lift(try rustCallWithError(FfiConverterTypeLightNodeError_lift) {
        uniffiCallStatus in
    uniffi_kovanica_ffi_fn_method_lightnode_produce_empty_block(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
    /**
     * A Merkle-inclusion proof for `tx_id` inside block `block_id_hex`,
     * encoded as a blob. `None` when either is unknown or the tx is absent.
     */
open func proveTx(blockIdHex: String, txIdHex: String)throws  -> Data?  {
    return try  FfiConverterOptionData.lift(try rustCallWithError(FfiConverterTypeLightNodeError_lift) {
        uniffiCallStatus in
    uniffi_kovanica_ffi_fn_method_lightnode_prove_tx(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(blockIdHex),
        FfiConverterString.lower(txIdHex),uniffiCallStatus
    )
})
}
    
    /**
     * Apply a blob produced by [`Self::export_blocks`] (or any full node
     * speaking the same format). Records apply topologically; already-known
     * blocks are skipped. Returns how many were newly applied.
     */
open func receiveBlocks(blob: Data)throws  -> UInt32  {
    return try  FfiConverterUInt32.lift(try rustCallWithError(FfiConverterTypeLightNodeError_lift) {
        uniffiCallStatus in
    uniffi_kovanica_ffi_fn_method_lightnode_receive_blocks(
            self.uniffiCloneHandle(),
        FfiConverterData.lower(blob),uniffiCallStatus
    )
})
}
    
    /**
     * Accept a light-sync blob: header chain is verified for linkage,
     * monotonic timestamps and rising blue work (`require_pow` off — hybrid
     * staked blocks carry nominal work). Returns accepted header count.
     */
open func receiveLightSync(blob: Data)throws  -> UInt32  {
    return try  FfiConverterUInt32.lift(try rustCallWithError(FfiConverterTypeLightNodeError_lift) {
        uniffiCallStatus in
    uniffi_kovanica_ffi_fn_method_lightnode_receive_light_sync(
            self.uniffiCloneHandle(),
        FfiConverterData.lower(blob),uniffiCallStatus
    )
})
}
    
    /**
     * Write a full snapshot (UTXO + stake registry + blocks) to `path`.
     */
open func saveSnapshot(path: String)throws   {try rustCallWithError(FfiConverterTypeLightNodeError_lift) {
        uniffiCallStatus in
    uniffi_kovanica_ffi_fn_method_lightnode_save_snapshot(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(path),uniffiCallStatus
    )
}
}
    
    /**
     * The selected (heaviest) tip, lowercase hex.
     */
open func selectedTip()throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeLightNodeError_lift) {
        uniffiCallStatus in
    uniffi_kovanica_ffi_fn_method_lightnode_selected_tip(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
    /**
     * Transfer `amount` from actor `from_seed` to `to_seed`, sealed
     * immediately in a mined block.
     */
open func send(fromSeed: UInt64, amount: UInt64, toSeed: UInt64)throws  -> SendReceipt  {
    return try  FfiConverterTypeSendReceipt_lift(try rustCallWithError(FfiConverterTypeLightNodeError_lift) {
        uniffiCallStatus in
    uniffi_kovanica_ffi_fn_method_lightnode_send(
            self.uniffiCloneHandle(),
        FfiConverterUInt64.lower(fromSeed),
        FfiConverterUInt64.lower(amount),
        FfiConverterUInt64.lower(toSeed),uniffiCallStatus
    )
})
}
    
    /**
     * Transfer using an imported secret: the wallet passes its 32-byte
     * ed25519 seed as hex; the secret is used for this call only and never
     * stored. `to_address` accepts 64-hex or `kvnc…dag` form.
     */
open func sendFrom(signingSecretHex: String, amount: UInt64, toAddress: String)throws  -> SendReceipt  {
    return try  FfiConverterTypeSendReceipt_lift(try rustCallWithError(FfiConverterTypeLightNodeError_lift) {
        uniffiCallStatus in
    uniffi_kovanica_ffi_fn_method_lightnode_send_from(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(signingSecretHex),
        FfiConverterUInt64.lower(amount),
        FfiConverterString.lower(toAddress),uniffiCallStatus
    )
})
}
    
    /**
     * Receive the per-block subsidy coinbase on produced blocks under this
     * actor seed.
     */
open func setMinerSeed(seed: UInt64)throws   {try rustCallWithError(FfiConverterTypeLightNodeError_lift) {
        uniffiCallStatus in
    uniffi_kovanica_ffi_fn_method_lightnode_set_miner_seed(
            self.uniffiCloneHandle(),
        FfiConverterUInt64.lower(seed),uniffiCallStatus
    )
}
}
    
    /**
     * Adopt a validator identity from a 32-byte VRF seed. Bond stake via
     * [`Self::bond_stake`] before production draws can win.
     */
open func setValidatorSeed(seed: Data)throws   {try rustCallWithError(FfiConverterTypeLightNodeError_lift) {
        uniffiCallStatus in
    uniffi_kovanica_ffi_fn_method_lightnode_set_validator_seed(
            self.uniffiCloneHandle(),
        FfiConverterData.lower(seed),uniffiCallStatus
    )
}
}
    
    /**
     * Whether `address` MIGHT appear in the given light-synced block,
     * answered from locally stored filters (`None` = block not synced).
     * A `true` is a probabilistic hit worth fetching full blocks for.
     */
open func syncedFilterMatches(blockIdHex: String, address: String)throws  -> Bool?  {
    return try  FfiConverterOptionBool.lift(try rustCallWithError(FfiConverterTypeLightNodeError_lift) {
        uniffiCallStatus in
    uniffi_kovanica_ffi_fn_method_lightnode_synced_filter_matches(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(blockIdHex),
        FfiConverterString.lower(address),uniffiCallStatus
    )
})
}
    
    /**
     * Highest height among light-synced headers (`None` before any sync).
     */
open func syncedHeight() -> UInt64?  {
    return try!  FfiConverterOptionUInt64.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_kovanica_ffi_fn_method_lightnode_synced_height(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
    /**
     * Current tip set, lowercase hex.
     */
open func tips()throws  -> [String]  {
    return try  FfiConverterSequenceString.lift(try rustCallWithError(FfiConverterTypeLightNodeError_lift) {
        uniffiCallStatus in
    uniffi_kovanica_ffi_fn_method_lightnode_tips(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
    /**
     * Total bonded stake across all validators (tip view), in atoms.
     */
open func totalStake()throws  -> UInt64  {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeLightNodeError_lift) {
        uniffiCallStatus in
    uniffi_kovanica_ffi_fn_method_lightnode_total_stake(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
    /**
     * Unbond `amount` of this validator's stake back to the seed actor's own
     * address. Only matured bonds count (`UNBOND_MATURITY` blue heights after
     * bonding); oldest bonds are released first, change stays unfrozen.
     * Sealed immediately in a mined block.
     */
open func unbond(fromSeed: UInt64, amount: UInt64)throws  -> SendReceipt  {
    return try  FfiConverterTypeSendReceipt_lift(try rustCallWithError(FfiConverterTypeLightNodeError_lift) {
        uniffiCallStatus in
    uniffi_kovanica_ffi_fn_method_lightnode_unbond(
            self.uniffiCloneHandle(),
        FfiConverterUInt64.lower(fromSeed),
        FfiConverterUInt64.lower(amount),uniffiCallStatus
    )
})
}
    
    /**
     * This validator's VRF public key, lowercase hex, if a seed was set.
     */
open func validatorPublicKeyHex() -> String?  {
    return try!  FfiConverterOptionString.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_kovanica_ffi_fn_method_lightnode_validator_public_key_hex(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
    /**
     * Verify an inclusion-proof blob against the light-synced header of
     * `block_id_hex`: the proof must verify internally AND its merkle root
     * must equal the header's root. Unknown block → error.
     */
open func verifyTxProof(proofBlob: Data, blockIdHex: String)throws  -> Bool  {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeLightNodeError_lift) {
        uniffiCallStatus in
    uniffi_kovanica_ffi_fn_method_lightnode_verify_tx_proof(
            self.uniffiCloneHandle(),
        FfiConverterData.lower(proofBlob),
        FfiConverterString.lower(blockIdHex),uniffiCallStatus
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeLightNode: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = LightNode

    public static func lift(_ handle: UInt64) throws -> LightNode {
        return LightNode(unsafeFromHandle: handle)
    }

    public static func lower(_ value: LightNode) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> LightNode {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: LightNode, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLightNode_lift(_ handle: UInt64) throws -> LightNode {
    return try FfiConverterTypeLightNode.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLightNode_lower(_ value: LightNode) -> UInt64 {
    return FfiConverterTypeLightNode.lower(value)
}




/**
 * A summary of one block in this node's DAG — enough for wallets to render
 * history without holding payloads.
 */
public struct BlockInfo: Equatable, Hashable {
    /**
     * BLAKE3 block id, lowercase hex (commits to parents+work+ts+nonce+payload).
     */
    public var idHex: String
    /**
     * Parent ids, lowercase hex (sorted, de-duplicated, as `Block` stores them).
     */
    public var parentsHex: [String]
    /**
     * Which hybrid admission path produced it.
     */
    public var kind: BlockKind
    /**
     * Claimed work weight (nominal `1` for staked blocks).
     */
    public var work: U128Parts
    /**
     * Milliseconds since the UNIX epoch.
     */
    public var timestampMs: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * BLAKE3 block id, lowercase hex (commits to parents+work+ts+nonce+payload).
         */idHex: String, 
        /**
         * Parent ids, lowercase hex (sorted, de-duplicated, as `Block` stores them).
         */parentsHex: [String], 
        /**
         * Which hybrid admission path produced it.
         */kind: BlockKind, 
        /**
         * Claimed work weight (nominal `1` for staked blocks).
         */work: U128Parts, 
        /**
         * Milliseconds since the UNIX epoch.
         */timestampMs: UInt64) {
        self.idHex = idHex
        self.parentsHex = parentsHex
        self.kind = kind
        self.work = work
        self.timestampMs = timestampMs
    }

    

    
}

#if compiler(>=6)
extension BlockInfo: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeBlockInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> BlockInfo {
        return
            try BlockInfo(
                idHex: FfiConverterString.read(from: &buf), 
                parentsHex: FfiConverterSequenceString.read(from: &buf), 
                kind: FfiConverterTypeBlockKind.read(from: &buf), 
                work: FfiConverterTypeU128Parts.read(from: &buf), 
                timestampMs: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: BlockInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.idHex, into: &buf)
        FfiConverterSequenceString.write(value.parentsHex, into: &buf)
        FfiConverterTypeBlockKind.write(value.kind, into: &buf)
        FfiConverterTypeU128Parts.write(value.work, into: &buf)
        FfiConverterUInt64.write(value.timestampMs, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBlockInfo_lift(_ buf: RustBuffer) throws -> BlockInfo {
    return try FfiConverterTypeBlockInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBlockInfo_lower(_ value: BlockInfo) -> RustBuffer {
    return FfiConverterTypeBlockInfo.lower(value)
}


/**
 * Genesis parameters for a fresh light node.
 */
public struct LightConfig: Equatable, Hashable {
    /**
     * GHOSTDAG parameter `k` (merge depth).
     */
    public var k: UInt16
    /**
     * Per-block KVNC subsidy.
     */
    public var subsidy: UInt64
    /**
     * Genesis coinbase size minted to the founder actor.
     */
    public var founderAmount: UInt64
    /**
     * Founder actor seed (deterministic demo keys; real wallets keep custody
     * client-side — see module docs).
     */
    public var founderSeed: UInt64
    /**
     * Finality depth; `u64::MAX` disables finality pruning.
     */
    public var finalityDepth: UInt64
    /**
     * Payload pruning depth; keep ≥ `finality_depth`.
     */
    public var payloadPruningDepth: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * GHOSTDAG parameter `k` (merge depth).
         */k: UInt16, 
        /**
         * Per-block KVNC subsidy.
         */subsidy: UInt64, 
        /**
         * Genesis coinbase size minted to the founder actor.
         */founderAmount: UInt64, 
        /**
         * Founder actor seed (deterministic demo keys; real wallets keep custody
         * client-side — see module docs).
         */founderSeed: UInt64, 
        /**
         * Finality depth; `u64::MAX` disables finality pruning.
         */finalityDepth: UInt64, 
        /**
         * Payload pruning depth; keep ≥ `finality_depth`.
         */payloadPruningDepth: UInt64) {
        self.k = k
        self.subsidy = subsidy
        self.founderAmount = founderAmount
        self.founderSeed = founderSeed
        self.finalityDepth = finalityDepth
        self.payloadPruningDepth = payloadPruningDepth
    }

    

    
}

#if compiler(>=6)
extension LightConfig: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeLightConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> LightConfig {
        return
            try LightConfig(
                k: FfiConverterUInt16.read(from: &buf), 
                subsidy: FfiConverterUInt64.read(from: &buf), 
                founderAmount: FfiConverterUInt64.read(from: &buf), 
                founderSeed: FfiConverterUInt64.read(from: &buf), 
                finalityDepth: FfiConverterUInt64.read(from: &buf), 
                payloadPruningDepth: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: LightConfig, into buf: inout [UInt8]) {
        FfiConverterUInt16.write(value.k, into: &buf)
        FfiConverterUInt64.write(value.subsidy, into: &buf)
        FfiConverterUInt64.write(value.founderAmount, into: &buf)
        FfiConverterUInt64.write(value.founderSeed, into: &buf)
        FfiConverterUInt64.write(value.finalityDepth, into: &buf)
        FfiConverterUInt64.write(value.payloadPruningDepth, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLightConfig_lift(_ buf: RustBuffer) throws -> LightConfig {
    return try FfiConverterTypeLightConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLightConfig_lower(_ value: LightConfig) -> RustBuffer {
    return FfiConverterTypeLightConfig.lower(value)
}


/**
 * Result of an immediate send: which block sealed the transfer and its tx id.
 */
public struct SendReceipt: Equatable, Hashable {
    public var blockIdHex: String
    public var txIdHex: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(blockIdHex: String, txIdHex: String) {
        self.blockIdHex = blockIdHex
        self.txIdHex = txIdHex
    }

    

    
}

#if compiler(>=6)
extension SendReceipt: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSendReceipt: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SendReceipt {
        return
            try SendReceipt(
                blockIdHex: FfiConverterString.read(from: &buf), 
                txIdHex: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: SendReceipt, into buf: inout [UInt8]) {
        FfiConverterString.write(value.blockIdHex, into: &buf)
        FfiConverterString.write(value.txIdHex, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSendReceipt_lift(_ buf: RustBuffer) throws -> SendReceipt {
    return try FfiConverterTypeSendReceipt.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSendReceipt_lower(_ value: SendReceipt) -> RustBuffer {
    return FfiConverterTypeSendReceipt.lower(value)
}


/**
 * A 128-bit value split across two 64-bit halves — the FFI stand-in for the
 * protocol's `u128` fields (work weights, atom balances).
 */
public struct U128Parts: Equatable, Hashable {
    public var high: UInt64
    public var low: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(high: UInt64, low: UInt64) {
        self.high = high
        self.low = low
    }

    

    
}

#if compiler(>=6)
extension U128Parts: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeU128Parts: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> U128Parts {
        return
            try U128Parts(
                high: FfiConverterUInt64.read(from: &buf), 
                low: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: U128Parts, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.high, into: &buf)
        FfiConverterUInt64.write(value.low, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeU128Parts_lift(_ buf: RustBuffer) throws -> U128Parts {
    return try FfiConverterTypeU128Parts.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeU128Parts_lower(_ value: U128Parts) -> RustBuffer {
    return FfiConverterTypeU128Parts.lower(value)
}


/**
 * How a block was admitted.
 */

public enum BlockKind: Equatable, Hashable {
    
    /**
     * Proof-of-work path (hash meets target).
     */
    case pow
    /**
     * Stake-weighted VRF sortition path.
     */
    case staked





}

#if compiler(>=6)
extension BlockKind: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeBlockKind: FfiConverterRustBuffer {
    typealias SwiftType = BlockKind

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> BlockKind {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .pow
        
        case 2: return .staked
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: BlockKind, into buf: inout [UInt8]) {
        switch value {
        
        
        case .pow:
            writeInt(&buf, Int32(1))
        
        
        case .staked:
            writeInt(&buf, Int32(2))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBlockKind_lift(_ buf: RustBuffer) throws -> BlockKind {
    return try FfiConverterTypeBlockKind.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBlockKind_lower(_ value: BlockKind) -> RustBuffer {
    return FfiConverterTypeBlockKind.lower(value)
}



/**
 * Why a [`LightNode`] operation failed.
 */
public 
enum LightNodeError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case AlreadyInitialized
    case Hex(field: String
    )
    case BadSeedLength
    case Invalid(msg: String
    )
    case InsufficientFunds(needed: UInt64
    )
    case BadSecretLength(expected: UInt32, got: UInt32
    )
    case InsufficientStake(requested: UInt64, available: UInt64
    )
    case Node(msg: String
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension LightNodeError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeLightNodeError: FfiConverterRustBuffer {
    typealias SwiftType = LightNodeError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> LightNodeError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .AlreadyInitialized
        case 2: return .Hex(
            field: try FfiConverterString.read(from: &buf)
            )
        case 3: return .BadSeedLength
        case 4: return .Invalid(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 5: return .InsufficientFunds(
            needed: try FfiConverterUInt64.read(from: &buf)
            )
        case 6: return .BadSecretLength(
            expected: try FfiConverterUInt32.read(from: &buf), 
            got: try FfiConverterUInt32.read(from: &buf)
            )
        case 7: return .InsufficientStake(
            requested: try FfiConverterUInt64.read(from: &buf), 
            available: try FfiConverterUInt64.read(from: &buf)
            )
        case 8: return .Node(
            msg: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: LightNodeError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case .AlreadyInitialized:
            writeInt(&buf, Int32(1))
        
        
        case let .Hex(field):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(field, into: &buf)
            
        
        case .BadSeedLength:
            writeInt(&buf, Int32(3))
        
        
        case let .Invalid(msg):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .InsufficientFunds(needed):
            writeInt(&buf, Int32(5))
            FfiConverterUInt64.write(needed, into: &buf)
            
        
        case let .BadSecretLength(expected,got):
            writeInt(&buf, Int32(6))
            FfiConverterUInt32.write(expected, into: &buf)
            FfiConverterUInt32.write(got, into: &buf)
            
        
        case let .InsufficientStake(requested,available):
            writeInt(&buf, Int32(7))
            FfiConverterUInt64.write(requested, into: &buf)
            FfiConverterUInt64.write(available, into: &buf)
            
        
        case let .Node(msg):
            writeInt(&buf, Int32(8))
            FfiConverterString.write(msg, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLightNodeError_lift(_ buf: RustBuffer) throws -> LightNodeError {
    return try FfiConverterTypeLightNodeError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLightNodeError_lower(_ value: LightNodeError) -> RustBuffer {
    return FfiConverterTypeLightNodeError.lower(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt64: FfiConverterRustBuffer {
    typealias SwiftType = UInt64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionBool: FfiConverterRustBuffer {
    typealias SwiftType = Bool?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterBool.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterBool.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionData: FfiConverterRustBuffer {
    typealias SwiftType = Data?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterData.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterData.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeBlockInfo: FfiConverterRustBuffer {
    typealias SwiftType = BlockInfo?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeBlockInfo.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeBlockInfo.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_kovanica_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_kovanica_ffi_checksum_method_lightnode_balance_of_address() != 13509) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kovanica_ffi_checksum_method_lightnode_balance_of_seed() != 2697) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kovanica_ffi_checksum_method_lightnode_block_by_id() != 61413) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kovanica_ffi_checksum_method_lightnode_block_count() != 12981) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kovanica_ffi_checksum_method_lightnode_block_filter() != 27849) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kovanica_ffi_checksum_method_lightnode_bond_stake() != 41825) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kovanica_ffi_checksum_method_lightnode_chain_height() != 36538) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kovanica_ffi_checksum_method_lightnode_enable_hybrid() != 31711) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kovanica_ffi_checksum_method_lightnode_export_blocks() != 64729) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kovanica_ffi_checksum_method_lightnode_export_light_sync() != 32984) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kovanica_ffi_checksum_method_lightnode_filter_matches() != 44042) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kovanica_ffi_checksum_method_lightnode_hybrid_enabled() != 35199) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kovanica_ffi_checksum_method_lightnode_load_snapshot() != 23192) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kovanica_ffi_checksum_method_lightnode_my_stake() != 14958) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kovanica_ffi_checksum_method_lightnode_pending_unbond_height() != 48072) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kovanica_ffi_checksum_method_lightnode_produce_block() != 32605) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kovanica_ffi_checksum_method_lightnode_produce_empty_block() != 37908) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kovanica_ffi_checksum_method_lightnode_prove_tx() != 12721) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kovanica_ffi_checksum_method_lightnode_receive_blocks() != 58012) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kovanica_ffi_checksum_method_lightnode_receive_light_sync() != 51134) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kovanica_ffi_checksum_method_lightnode_save_snapshot() != 41165) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kovanica_ffi_checksum_method_lightnode_selected_tip() != 22558) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kovanica_ffi_checksum_method_lightnode_send() != 59372) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kovanica_ffi_checksum_method_lightnode_send_from() != 26817) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kovanica_ffi_checksum_method_lightnode_set_miner_seed() != 15947) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kovanica_ffi_checksum_method_lightnode_set_validator_seed() != 59967) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kovanica_ffi_checksum_method_lightnode_synced_filter_matches() != 35807) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kovanica_ffi_checksum_method_lightnode_synced_height() != 46770) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kovanica_ffi_checksum_method_lightnode_tips() != 38486) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kovanica_ffi_checksum_method_lightnode_total_stake() != 40840) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kovanica_ffi_checksum_method_lightnode_unbond() != 38383) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kovanica_ffi_checksum_method_lightnode_validator_public_key_hex() != 29090) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kovanica_ffi_checksum_method_lightnode_verify_tx_proof() != 40302) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kovanica_ffi_checksum_constructor_lightnode_new() != 20948) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureKovanicaFfiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all