# Android
android.nonTransitiveRClass = true
android.nonFinalResIds = true

# Kotlin
kotlin.code.style = official

# JVM
org.gradle.jvmargs = -Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel = true
org.gradle.configureondemand = true

# Build cache
android.enableBuildCache = true

# UniFFI / JNA
jna.nosys = true