//! Shared Tauri shell for the Kovanica consoles.
//!
//! Kovanica Console and Kovanica Enterprise Console are two products that ship
//! from the same shell: an identical `tauri::Builder` runtime, the same security
//! posture, and — today — no Rust-side commands and no plugins. Keeping the
//! entry point in one place means the two consoles cannot drift apart: a change
//! to how the shell starts, or to what it registers, applies to both.
//!
//! The runtime is pinned to [`Wry`] because `tauri::Context<R>` has no default
//! type parameter. Naming it here lets `tauri::generate_context!()` at the call
//! site infer `R` without a turbofish; a fully generic helper would leave `R`
//! unconstrained and fail to compile with "type annotations needed".

use tauri::Wry;

/// Start the console shell with the Tauri context generated by the calling app.
///
/// Each console's `lib.rs` is a one-liner:
///
/// ```ignore
/// #[cfg_attr(mobile, tauri::mobile_entry_point)]
/// pub fn run() {
///     kovanica_console_shell::run(tauri::generate_context!());
/// }
/// ```
pub fn run(context: tauri::Context<Wry>) {
    tauri::Builder::default()
        .run(context)
        .expect("error while running tauri application");
}
