[package]
name = "kovanica-types"
description = "Core data types for the Kovanica protocol (addresses, txs, UTXOs, assets) + canonical transaction codec"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true

[dependencies]
serde = { workspace = true }
hex = { workspace = true }
thiserror = { workspace = true }
blake3 = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }