//! Consumer test for the shared golden-vector file `protocol/testvectors/vectors.json`.
//!
//! The file is generated by `examples/gen_testvectors.rs` and loaded read-only by
//! every implementation. This test re-derives every Rust-side value and fails
//! loudly on drift: if the file and the code disagree, the code changed the wire
//! format (a finding), not the vector.
//!
//! Regenerate with:
//!
//! ```sh
//! cargo run -p kovanica-wallet --example gen_testvectors \
//!   > testvectors/vectors.json
//! ```

use std::path::PathBuf;

use kovanica_state::tx::{AssetId, OutPoint, StealthExt, Transaction, TxId, TxInput, TxOutput};
use kovanica_state::{Address, HtlcScript, KeyPair, MultisigScript, VaultScript};
use kovanica_wallet::Wallet;
use serde_json::Value;

fn load() -> Value {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../testvectors/vectors.json");
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
    serde_json::from_str(&text).expect("vectors.json is valid JSON")
}

fn vectors_of<'a>(doc: &'a Value, kind: &str) -> Vec<&'a Value> {
    doc["vectors"]
        .as_array()
        .expect("vectors is an array")
        .iter()
        .filter(|v| v["kind"] == kind)
        .collect()
}

fn s(v: &Value, key: &str) -> String {
    v[key]
        .as_str()
        .unwrap_or_else(|| panic!("missing string field {key}"))
        .to_string()
}

fn u(v: &Value, key: &str) -> u64 {
    v[key]
        .as_u64()
        .unwrap_or_else(|| panic!("missing number field {key}"))
}

fn versioned(version: u8, payload: [u8; 32]) -> Address {
    let mut raw = [0u8; 33];
    raw[0] = version;
    raw[1..].copy_from_slice(&payload);
    Address::from_versioned_bytes(raw)
}

fn pk(k: u64) -> [u8; 32] {
    *KeyPair::from_u64(k).address().payload()
}

#[test]
fn derivation_vectors_match_rust() {
    let doc = load();
    let cases = vectors_of(&doc, "derivation");
    assert!(!cases.is_empty(), "no derivation vectors");

    for case in cases {
        let name = s(case, "name");
        let wallet = Wallet::from_mnemonic_at(
            &s(case, "mnemonic"),
            &s(case, "passphrase"),
            u(case, "index") as u32,
        )
        .unwrap_or_else(|e| panic!("{name}: derivation failed: {e}"));

        assert_eq!(
            hex::encode(wallet.public_key()),
            s(case, "pubkey_hex"),
            "{name}: pubkey drift"
        );
        assert_eq!(
            wallet.address().to_kvnc(),
            s(case, "address"),
            "{name}: kvnc drift"
        );
        assert_eq!(
            wallet.address().to_hex(),
            s(case, "address_hex"),
            "{name}: versioned-hex drift"
        );
    }
}

#[test]
fn script_vectors_match_rust() {
    let doc = load();

    for case in vectors_of(&doc, "multisig") {
        let m = u(case, "m") as u8;
        let keys: Vec<[u8; 32]> = case["keys"]
            .as_array()
            .expect("keys")
            .iter()
            .map(|k| pk(k.as_u64().expect("key index")))
            .collect();
        let script = MultisigScript::new(m, keys).expect("multisig constructs");
        assert_eq!(hex::encode(script.encode()), s(case, "script_hex"));
        assert_eq!(
            hex::encode(script.script_hash()),
            s(case, "script_hash_hex")
        );
        assert_eq!(script.address().to_kvnc(), s(case, "address"));
        assert_eq!(script.address().to_hex(), s(case, "address_hex"));
    }

    for case in vectors_of(&doc, "htlc") {
        let script = HtlcScript::new(
            [0x42u8; 32],
            pk(u(case, "recipient_key")),
            pk(u(case, "sender_key")),
            u(case, "timeout") as u32,
        )
        .expect("htlc constructs");
        assert_eq!(hex::encode(script.bytes()), s(case, "script_hex"));
        assert_eq!(
            hex::encode(script.script_hash()),
            s(case, "script_hash_hex")
        );
        assert_eq!(script.address().to_kvnc(), s(case, "address"));
        assert_eq!(script.address().to_hex(), s(case, "address_hex"));
    }

    for case in vectors_of(&doc, "vault") {
        let script = VaultScript::new(
            u(case, "unlock_height") as u32,
            u(case, "csv") as u32,
            pk(u(case, "owner_key")),
        )
        .expect("vault constructs");
        assert_eq!(hex::encode(script.bytes()), s(case, "script_hex"));
        assert_eq!(
            hex::encode(script.script_hash()),
            s(case, "script_hash_hex")
        );
        assert_eq!(script.address().to_kvnc(), s(case, "address"));
        assert_eq!(script.address().to_hex(), s(case, "address_hex"));
    }
}

#[test]
fn address_vectors_match_rust() {
    let doc = load();
    for case in vectors_of(&doc, "address") {
        let payload: [u8; 32] = hex::decode(s(case, "payload_hex"))
            .expect("payload hex")
            .try_into()
            .expect("32-byte payload");
        let version = u(case, "version") as u8;
        // `legacy-32-p2pk` renders from the bare 32-byte form; every other
        // address vector uses the versioned 33-byte form.
        let address = if s(case, "name") == "legacy-32-p2pk" {
            Address::p2pk(payload)
        } else {
            versioned(version, payload)
        };
        assert_eq!(address.to_kvnc(), s(case, "address"));
        assert_eq!(address.to_hex(), s(case, "address_hex"));
        assert_eq!(
            Address::parse(&s(case, "address")).expect("parses"),
            address,
            "{}: round-trip",
            s(case, "name")
        );
    }
}

#[test]
fn transaction_vectors_match_rust() {
    let doc = load();

    for case in vectors_of(&doc, "transaction") {
        let name = s(case, "name");
        let tx = match name.as_str() {
            "native-multi-asset" => {
                let alice = versioned(0x00, [0xAAu8; 32]);
                let bob = versioned(0x00, [0xBBu8; 32]);
                let asset = AssetId::from_bytes([0xEEu8; 32]);
                Transaction::new(
                    vec![
                        TxInput::new(OutPoint::new(TxId::from_bytes([0x11u8; 32]), 0), Vec::new()),
                        TxInput::new(OutPoint::new(TxId::from_bytes([0x22u8; 32]), 1), Vec::new()),
                    ],
                    vec![
                        TxOutput::native(1_000_000_000, alice),
                        TxOutput::new(500, Some(asset), bob),
                    ],
                    b"vector".to_vec(),
                )
            }
            "stealth-lock-1000-seq-7" => {
                let owner = versioned(0x03, [0x5Du8; 32]);
                let alice = versioned(0x00, [0xAAu8; 32]);
                let ext = StealthExt {
                    r: [0x5Au8; 32],
                    view_tag: 0x42,
                    p: [0x5Cu8; 32],
                };
                Transaction::new_with_lock(
                    vec![TxInput::new(
                        OutPoint::new(TxId::from_bytes([0x33u8; 32]), 2),
                        Vec::new(),
                    )],
                    vec![
                        TxOutput::native(777, alice),
                        TxOutput::stealth(123, owner, ext),
                    ],
                    b"stealth".to_vec(),
                    1000,
                    7,
                )
            }
            other => panic!("unknown transaction vector {other}"),
        };

        assert_eq!(
            hex::encode(tx.encode()),
            s(case, "encode_hex"),
            "{name}: encode"
        );
        assert_eq!(
            hex::encode(tx.sighash()),
            s(case, "sighash_hex"),
            "{name}: sighash"
        );

        if let Some(sig) = case.get("signature_hex").and_then(|v| v.as_str()) {
            let signer = KeyPair::from_u64(1);
            assert_eq!(
                hex::encode(signer.sign(&tx.sighash())),
                sig,
                "{name}: Ed25519 signature"
            );
            assert_eq!(signer.address().to_kvnc(), s(case, "signer_address"));
        }
    }
}
