//! Consumer test for the shared golden-vector file `protocol/testvectors/vectors.json`.
//!
//! The canonical file lives in the Rust core tree and is generated by
//! `protocol/crates/kovanica-wallet/examples/gen_testvectors.rs`. The SDK must
//! reproduce every derivation and script vector byte-for-byte; a mismatch here
//! means the published SDK and the node would derive different keys or build
//! different scripts — a finding, never a reason to edit the vector.
//!
//! The path is workspace-relative (`sdk/crates/kovanica-keys` → repo root →
//! `protocol/testvectors`). It is only present in the monorepo; standalone
//! consumers of the published crate are unaffected because this is a `tests/`
//! integration test.

use std::path::PathBuf;

use kovanica_keys::scripts::{HtlcScript, MultisigScript, VaultScript};
use kovanica_keys::{decode_address, to_kvnc, Keypair, Mnemonic};
use serde_json::Value;

fn load() -> Value {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../../protocol/testvectors/vectors.json");
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
    serde_json::from_str(&text).expect("vectors.json is valid JSON")
}

fn vectors_of<'a>(doc: &'a Value, kind: &str) -> Vec<&'a Value> {
    doc["vectors"]
        .as_array()
        .expect("vectors is an array")
        .iter()
        .filter(|v| v["kind"] == kind)
        .collect()
}

fn s(v: &Value, key: &str) -> String {
    v[key].as_str().expect("string field").to_string()
}

fn u(v: &Value, key: &str) -> u64 {
    v[key].as_u64().expect("number field")
}

/// Deterministic pubkey `[k LE, 0…0]`, matching the node's `KeyPair::from_u64`.
fn pk(k: u64) -> [u8; 32] {
    let mut bytes = [0u8; 32];
    bytes[..8].copy_from_slice(&k.to_le_bytes());
    ed25519_dalek::SigningKey::from_bytes(&bytes)
        .verifying_key()
        .to_bytes()
}

#[test]
fn sdk_derivation_vectors_match() {
    let doc = load();
    let cases = vectors_of(&doc, "derivation");
    assert!(!cases.is_empty(), "no derivation vectors");

    for case in cases {
        let name = s(case, "name");
        let mnemonic = Mnemonic::from_phrase(&s(case, "mnemonic")).expect("valid phrase");
        let kp =
            Keypair::from_mnemonic_at(&mnemonic, &s(case, "passphrase"), u(case, "index") as u32);

        assert_eq!(
            hex::encode(kp.public_key().0),
            s(case, "pubkey_hex"),
            "{name}: pubkey drift"
        );
        assert_eq!(
            to_kvnc(&kp.address()),
            s(case, "address"),
            "{name}: kvnc drift"
        );
        assert_eq!(
            kp.address().to_hex(),
            s(case, "address_hex"),
            "{name}: versioned-hex drift"
        );
        assert_eq!(
            decode_address(&s(case, "address")).expect("address parses"),
            kp.address(),
            "{name}: round-trip"
        );
    }
}

#[test]
fn sdk_script_vectors_match() {
    let doc = load();

    for case in vectors_of(&doc, "multisig") {
        let keys: Vec<[u8; 32]> = case["keys"]
            .as_array()
            .expect("keys")
            .iter()
            .map(|k| pk(k.as_u64().expect("key index")))
            .collect();
        let script = MultisigScript::new(u(case, "m") as u8, keys).expect("multisig");
        assert_eq!(hex::encode(script.encode()), s(case, "script_hex"));
        assert_eq!(
            hex::encode(script.script_hash()),
            s(case, "script_hash_hex")
        );
        assert_eq!(to_kvnc(&script.address()), s(case, "address"));
        assert_eq!(script.address().to_hex(), s(case, "address_hex"));
    }

    for case in vectors_of(&doc, "htlc") {
        let script = HtlcScript::new(
            [0x42u8; 32],
            pk(u(case, "recipient_key")),
            pk(u(case, "sender_key")),
            u(case, "timeout") as u32,
        )
        .expect("htlc");
        assert_eq!(hex::encode(script.bytes()), s(case, "script_hex"));
        assert_eq!(
            hex::encode(script.script_hash()),
            s(case, "script_hash_hex")
        );
        assert_eq!(to_kvnc(&script.address()), s(case, "address"));
        assert_eq!(script.address().to_hex(), s(case, "address_hex"));
    }

    for case in vectors_of(&doc, "vault") {
        let script = VaultScript::new(
            u(case, "unlock_height") as u32,
            u(case, "csv") as u32,
            pk(u(case, "owner_key")),
        )
        .expect("vault");
        assert_eq!(hex::encode(script.bytes()), s(case, "script_hex"));
        assert_eq!(
            hex::encode(script.script_hash()),
            s(case, "script_hash_hex")
        );
        assert_eq!(to_kvnc(&script.address()), s(case, "address"));
        assert_eq!(script.address().to_hex(), s(case, "address_hex"));
    }
}
